# Setup
title:               Subwayway
tagline:             'Embedded DEV'
description:         'Subwayway'
url:                 https://subwayway.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

category_dir: category/
tag_dir: tag/

# About/contact
author:
  name:              Subwayway
  url:               https://github.com/Subwayway
  email:

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
